# Change these first
owner: KPGhelpdesk # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Paardekooper Servicedesk Portal
    url: https://pdkg.topdesk.net
  - name: Paardekooper Webshop
    url: https://www.paardekooper.nl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pdkg.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Paardekooper System Status Overview
  introTitle: "**SYSTEM STATUS OVERVIEW**"
  introMessage: This page shows the status of Paardekooper key systems.
  themeUrl: https://status.pdkg.org/custom-theme.css
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
